name: Compile GBA
on: [push]
jobs:
 Compile-GBA:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: getting devkitarm
        run: |
         docker run --cidfile=c.cid devkitpro/devkitarm:latest "echo" "getting c.cid"
         docker cp -L $(cat c.cid):/opt/devkitpro - | tar -x
         rm c.cid

      - name: getting butano
        run: git clone https://github.com/GValiente/butano.git /opt/butano
        env:
         GIT_SSL_NO_VERIFY: 1

      - name: install dependencies
        run: |
         sudo apt-get update && \
         sudo apt-get install make -y --no-install-recommends && \
         sudo apt-get install git  -y --no-install-recommends && \
         sudo apt-get install python3 -y --no-install-recommends  && \
         sudo apt-get install python-is-python3 -y --no-install-recommends  && \
         sudo apt-get clean

      - name: build docker image
        run: make
        env:
         DEVKITPRO: /opt/devkitpro
         DEVKITARM: /opt/devkitpro/devkitARM
         LIBBUTANOBASE: /opt/butano
