name: Compile GBA

on:
  push:
    branches: [master]

jobs:
 Compile-GBA:
    runs-on: ubuntu-20.04
    container: devkitpro/devkitarm
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: getting butano
        run: git clone https://github.com/GValiente/butano.git /opt/butano
        env:
         GIT_SSL_NO_VERIFY: 1

      - name: install dependencies
        run: |
         sudo apt-get update
         sudo apt-get install python3 python-is-python3 -y --no-install-recommends

      - name: make the .gba
        run: make
        env:
         DEVKITPRO: /opt/devkitpro
         DEVKITARM: /opt/devkitpro/devkitARM
         LIBBUTANOBASE: /opt/butano
